### ISSUE TITLE
Not able to access the repo to submit a PR.

### ISSUE THREAD

**Issue by amcasari** [osbd/osbd-2019#2]
Hello!

I'm not able to submit a PR to the repo. Is the access open?

Cheers,
Amanda

**Comment by magsol** [comment]
Hi there! It should be; Carol was able to submit a PR. Is there an error message you're getting or some other indicator that the repo is closed?

**Comment by amcasari** [comment]
Hello. Shaking the rust off. Figured it out. Thanks much!
